baseURL: https://aquatictw.com

languageCode: en-us
title: "Aquatic 的部落格"

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts

languages:
  zh-tw:
    languageName: Chinese 
    weight: 1
DefaultContentLanguage: zh-tw 

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

# Site parameters
params:
  background: /images/site/eva.jpg
  logo:
    main: /images/site/website-icon.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 7

  features:
    darkMode:
      enable: true

    portfolio:
      enable: true 

    # Enable and configure blog posts
    blog:
      enable: true
      showAuthor: true
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true

    # Enable & configure "Notes" features
    notes:
      enable: false 

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: false

    # Enable Analytics
    analytics:
      enabled: false 

    # Enable Support
    support:
      enable: false
      services:
        kofi:
          user: hossainemruz
          text: Tip Me
          textColor: '#f9fafc'
          backgroundColor: '#248aaa'

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    # Show tags under the post title
    tags:
      enable: true
      on_card: true # enables tags in post cards

    # Specify whether to show flag in the language selector. Default is true.
    flags:
      enable: true

    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: true

    # Enable this to create flowcharts using shortcodes.
    flowchart:
      enable: true
      services:
        # Uncomment for `mermaid` shortcode.
        mermaid:
          # For config options, see: https://mermaid-js.github.io/mermaid/#/Setup?id=configuration
          theme: forest

    # Enable this to create mathematic expressions using `$$` blocks
    math:
      enable: true
      services:
        # https://katex.org/docs/autorender.html#api for more configurations
        katex:
          delimiters:
            - left: $$
              right: $$
              display: true
            - left: \\[
              right: \\]
              display: true
            - left: $
              right: $
              display: false
            - left: \\(
              right: \\)
              display: false

    syntaxHighlight:
      enable: true
      services:
        hljs:
          # see: https://highlightjs.readthedocs.io/en/latest/api.html#configure
          noHighlightRe: /^no-highlight$/i

    # Enable to use `video-player` shortcode
    videoPlayer:
      enable: true
      services:
        plyr:
    readingTime:
      enable: false
    
    # Number of posts to show to each page. Default is "12"
    pagination:
       maxPostsPerPage: 12


  footer:
    enable: true
    template: footer.html
    navigation:
      enable: true
      customMenus: true
    contactMe:
      enable: true
    credentials:
      enable: true 
    newsletter:
      enable: false

