version: "3.3"

services:
  web:
    image: joseluisq/static-web-server:2
    container_name: static-web-server 
    volumes:
      - /home/self-host/hugo/hugo-blog/public:/public
    networks:
      - web_apps 

networks:
  web_apps:
    external: true
